### ISSUE TITLE
could support chinese?

### ISSUE THREAD

**Issue by tianlu1677** [david-mccullars/text_rank#2]
For example, when i use it   `TextRank.extract_keywords("中国的海岸线很长")`,   I just get `{}`。 So what should I do

**Comment by david-mccullars** [comment]
You should be able to write a custom Tokenizer that will properly handle Chinese, e.g.:

```ruby
TextRank.extract_keywords_advanced("中国的海岸线很长", tokenizers: [CustomTokenizer])
```

See https://github.com/david-mccullars/text_rank/tree/main/lib/text_rank/tokenizer for examples of existing tokenizers.

You may also want to add custom token filters to strip out "noise".  If you get something working feel free to submit a PR.
